version: '3.6'

services:
    mongo:
        image: mongo:latest
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=h5pnodejs
        # ports:
        #     - '27017:27017'
        volumes:
            - mongodb_data:/data/db
    minio:
        image: minio/minio:latest
        volumes:
            - minio_data:/data
        # ports:
        #      - '9000:9000'
        command: ['server', '/data']
        environment:
            - MINIO_ACCESS_KEY=minioaccesskey
            - MINIO_SECRET_KEY=miniosecret
    redis:
        image: 'redis:alpine'
        command: 'redis-server --appendonly yes'
        # ports:
        #     - '6379:6379'
        volumes:
            - redis_data:/data
    # Creates buckets for S3
    minio_init:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc config host add h5pminio http://minio:9000 minioaccesskey miniosecret --api S3v4;
            /usr/bin/mc mb h5pminio/testbucket1;
            /usr/bin/mc mb h5pminio/tempbucket1;
            /usr/bin/mc mb h5pminio/libbucket1;
            exit 0;
            "
    h5p:
        build: ../
        # ports:
        #     - '8080:8080'
        depends_on:
            - mongo
            - minio
            - minio_init
            - redis
        environment:
            - CONTENTSTORAGE=mongos3
            - AWS_ACCESS_KEY_ID=minioaccesskey
            - AWS_SECRET_ACCESS_KEY=miniosecret
            - AWS_S3_ENDPOINT=http://minio:9000
            - AWS_S3_MAX_FILE_LENGTH=100
            - CONTENT_AWS_S3_BUCKET=testbucket1
            - TEMPORARYSTORAGE=s3
            - TEMPORARY_AWS_S3_BUCKET=tempbucket1
            - MONGODB_URL=mongodb://mongo:27017
            - MONGODB_DB=testdb1
            - MONGODB_USER=root
            - MONGODB_PASSWORD=h5pnodejs
            - CONTENT_MONGO_COLLECTION=h5p
            - CACHE=redis
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_DB=0
            - LOCK=redis
            - LOCK_REDIS_HOST=redis
            - LOCK_REDIS_PORT=6379
            - LOCK_REDIS_DB=1
            - LIBRARYSTORAGE=mongos3
            - LIBRARY_MONGO_COLLECTION=h5plibraries
            - LIBRARY_AWS_S3_BUCKET=libbucket1
        volumes:
            - h5p_data:/home/node/h5p-nodejs-library/h5p
    loadbalancer:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - h5p
        ports:
            - 8080:8080

volumes:
    mongodb_data:
    minio_data:
    redis_data:
    h5p_data:
