# Needed for the integration tests of the h5p-mongos3 package.
# Run with docker-compose -f scripts/mongo-s3-docker-compose.yml up
version: '3.6'

services:
    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: h5pnodejs
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/db
            
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: h5pnodejs
            ME_CONFIG_MONGODB_URL: mongodb://root:h5pnodejs@mongo:27017/
            ME_CONFIG_BASICAUTH: false

    minio1:
        image: minio/minio:latest
        volumes:
            - minio_data:/data
        ports:
            - 9000:9000
            - 9001:9001
        command: ['server', '/data', '--console-address', ':9001']
        environment:
            MINIO_ACCESS_KEY: minioaccesskey
            MINIO_SECRET_KEY: miniosecret

volumes:
    mongodb_data:
    minio_data:
