version: '3.6'

services:
    mongo:
        image: mongo:latest
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=h5pnodejs
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data:/data/db
    
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: h5pnodejs
            ME_CONFIG_MONGODB_URL: mongodb://root:h5pnodejs@mongo:27017/
            ME_CONFIG_BASICAUTH: false
    
    minio:
        image: minio/minio:latest
        volumes:
            - minio_data:/data
        ports:
            - '9000:9000'
        command: ['server', '/data', '--console-address', ':9001']
        environment:
            - MINIO_ACCESS_KEY=minioaccesskey
            - MINIO_SECRET_KEY=miniosecret
    
    redis:
        image: 'redis:alpine'
        command: 'redis-server --appendonly yes'
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
    
    # Creates buckets for S3
    minio_init:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc config host add h5pminio http://minio:9000 minioaccesskey miniosecret --api S3v4;
            /usr/bin/mc mb h5pminio/testbucket1;
            /usr/bin/mc mb h5pminio/tempbucket1;
            /usr/bin/mc mb h5pminio/libbucket1;
            exit 0;
            "

volumes:
    mongodb_data:
    minio_data:
    redis_data:
