# Needed for the integration tests of the h5p-mongos3 package.
# Run with docker-compose -f scripts/mongo-s3-docker-compose.yml up
version: '3.6'

services:
    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: h5pnodejs
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/db
    minio1:
        image: minio/minio:latest
        volumes:
            - minio_data:/data
        ports:
            - 9000:9000
            - 9001:9001
        command: ['server', '/data']
        environment:
            MINIO_ACCESS_KEY: minioaccesskey
            MINIO_SECRET_KEY: miniosecret

volumes:
    mongodb_data:
    minio_data:
