import { open } from 'fs/promises';
import { filetypeextension } from 'magic-bytes.js';
import { lookup as mimeLookup } from 'mime-types';
import path from 'path';
import H5pError from './helpers/H5pError';
import Logger from './helpers/Logger';
import { H5PFile } from './types';

const log = new Logger('contentFileValidation');

/**
 * Formats that share magic bytes but have unrelated MIME types, so they
 * cannot be matched via mime-types lookups. Each group is fully
 * bidirectional: every extension in a group is equivalent to every other.
 */
const magicByteEquivalents: string[][] = [
    ['webm', 'mkv', 'mka', 'mks'],
    ['png', 'apng']
];

/**
 * Patterns that indicate dangerous XML/SVG/HTML content which could enable
 * XSS attacks when disguised as other file types.
 */
const dangerousTextPatterns = [
    '<?xml',
    '<svg',
    '<!doctype',
    '<html',
    '<script'
];

/**
 * Validates that a file's content matches its claimed extension. Automatically
 * chooses the appropriate validation method based on whether the file data is
 * available as an in-memory buffer or as a path to a temporary file on disk.
 *
 * @param file the uploaded file to validate; must have either `data` (buffer)
 * or `tempFilePath` set
 * @throws H5pError with errorId 'upload-validation-error' if the file has
 * neither data nor tempFilePath, or if content validation fails
 */
export async function validateContent(file: H5PFile): Promise<void> {
    if (file.data) {
        await validateBufferContent(file.data, file.name);
    } else if (file.tempFilePath) {
        await validateFileContent(file.tempFilePath);
    } else {
        log.error(
            `File has no data or tempFilePath for validation: ${file.name}`
        );
        throw new H5pError('upload-validation-error', {}, 400);
    }
}

/**
 * Validates that the content of a file matches its claimed extension. Uses
 * magic byte detection via magic-bytes.js to identify binary file types and
 * rejects mismatches. Also detects XML/SVG/HTML content disguised as other file
 * types, which could enable XSS attacks.
 *
 * This validator checks all extensions in the configured content whitelist, not
 * a hardcoded set, so custom whitelist entries are also validated.
 *
 * Note that the filePath parameter is not fully sanitized, so this function is
 * not suitable for direct use with user input without additional checks. It is
 * designed to be used with file paths generated by trusted middleware (e.g.
 * temporary files created during uploads).
 *
 * @param filePath absolute path to the file to validate; not suitable for user
 * input without sanitization
 * @throws H5pError with errorId 'upload-validation-error' if the file content
 * does not match its extension
 */
export async function validateFileContent(filePath: string): Promise<void> {
    // Validate and normalize the file path to guard against malformed or
    // relative paths. All callers are expected to pass absolute paths
    // produced by trusted middleware (e.g. file-upload temp files).
    if (!filePath || !filePath.trim() || !path.isAbsolute(filePath)) {
        log.error(
            `Invalid file path provided to validateFileContent: ${filePath}`
        );
        throw new H5pError('upload-validation-error', {}, 400);
    }
    const resolvedPath = path.resolve(filePath);

    const ext = path.extname(resolvedPath).toLowerCase().replace(/^\./, '');
    if (!ext) {
        return;
    }

    const fileHandle = await open(resolvedPath, 'r');
    try {
        const buffer = Buffer.alloc(1024);
        const { bytesRead } = await fileHandle.read(buffer, 0, 1024, 0);
        if (bytesRead === 0) {
            return;
        }
        validateContentBytes(buffer.subarray(0, bytesRead), ext, resolvedPath);
    } finally {
        await fileHandle.close();
    }
}

/**
 * Validates that a buffer's content matches its expected file type. Inspects
 * the first 1024 bytes of the in-memory buffer directly (the same amount
 * {@link validateFileContent} reads from disk), so it never has to write the
 * (potentially large) buffer to disk just to validate it.
 *
 * @param buffer the file content to validate; must be non-empty
 * @param filename the original filename, used to determine the extension for
 * content-type validation
 * @throws H5pError with errorId 'upload-validation-error' if the buffer is
 * empty or if the content fails validation
 */
export async function validateBufferContent(
    buffer: Buffer,
    filename: string
): Promise<void> {
    if (!buffer || buffer.length === 0) {
        log.error(
            `Invalid buffer provided to validateBufferContent: empty or undefined`
        );
        throw new H5pError('upload-validation-error', {}, 400);
    }

    const ext = path.extname(filename).toLowerCase().replace(/^\./, '');
    if (!ext) {
        return;
    }

    validateContentBytes(buffer.subarray(0, 1024), ext, filename);
}

/**
 * Shared magic-byte / dangerous-content check used by both
 * {@link validateFileContent} (reading from disk) and
 * {@link validateBufferContent} (reading from memory).
 * @param data the first bytes of the file (up to 1024)
 * @param ext the claimed extension (without leading dot), already lowercased
 * @param label a path or filename used only for log messages
 */
function validateContentBytes(data: Buffer, ext: string, label: string): void {
    // Detect the actual file type using magic bytes
    const detectedExtensions = filetypeextension([...data] as number[]).map(
        (e) => e.replace(/^\./, '')
    );

    if (detectedExtensions.length > 0) {
        // The library detected a file type — check it matches
        // the claimed extension
        if (extensionMatchesDetected(ext, detectedExtensions)) {
            // Even when the extension matches, text-based detections
            // (e.g. a BOM causing magic-bytes to return "txt") still
            // need the dangerous-content check. A UTF-8 BOM followed
            // by <html>…</html> would otherwise slip through.
            if (
                detectedExtensions.includes('txt') &&
                looksLikeXmlOrHtml(data)
            ) {
                log.info(
                    `File detected as text but contains XML/HTML content. Rejecting file: ${label}`
                );
                throw new H5pError('upload-validation-error', {}, 400);
            }
            return;
        }
        log.info(
            `File content mismatch: ${label} claims to be .${ext} but detected as ${detectedExtensions.join(', ')}. Rejecting file.`
        );
        throw new H5pError('upload-validation-error', {}, 400);
    }

    // magic-bytes.js returned nothing — file may be text-based
    // or an unrecognized binary format. Check for dangerous
    // XML/SVG/HTML content that could enable XSS regardless of
    // the claimed extension.
    if (looksLikeXmlOrHtml(data)) {
        log.info(
            `File contains XML/HTML content but claims to be .${ext}. Rejecting file: ${label}`
        );
        throw new H5pError('upload-validation-error', {}, 400);
    }
}

/**
 * Extracts the subtype portion of a MIME type string (e.g. "mp4" from
 * "video/mp4").
 */
function getMimeSubtype(mimeType: string): string | undefined {
    const slash = mimeType.indexOf('/');
    return slash >= 0 ? mimeType.substring(slash + 1) : undefined;
}

/**
 * Checks whether the claimed extension matches any of the detected
 * extensions using three tiers:
 * 1. Direct match — the claimed extension is in the detected list.
 * 2. MIME match — mime-types resolves both extensions to the same MIME
 *    type or to types that share the same subtype (e.g. video/mp4 and
 *    audio/mp4).
 * 3. Residual map — a small list of formats that share magic bytes but
 *    have unrelated MIME types (e.g. webm/mkv, png/apng).
 */
export function extensionMatchesDetected(
    claimedExt: string,
    detectedExtensions: string[]
): boolean {
    // Tier 1: direct match
    if (detectedExtensions.includes(claimedExt)) {
        return true;
    }

    // Tier 2: MIME type / subtype match
    const claimedMime = mimeLookup(claimedExt);
    if (claimedMime) {
        const claimedSubtype = getMimeSubtype(claimedMime);
        for (const det of detectedExtensions) {
            const detMime = mimeLookup(det);
            if (!detMime) continue;
            if (detMime === claimedMime) return true;
            if (claimedSubtype && claimedSubtype === getMimeSubtype(detMime)) {
                return true;
            }
        }
    }

    // Tier 3: residual magic-byte equivalents
    for (const group of magicByteEquivalents) {
        if (group.includes(claimedExt)) {
            if (detectedExtensions.some((det) => group.includes(det))) {
                return true;
            }
        }
    }

    return false;
}

/**
 * Checks if the beginning of a buffer looks like XML, SVG, HTML, or
 * script content that could be used for XSS attacks.
 */
function looksLikeXmlOrHtml(buffer: Buffer): boolean {
    const head = buffer
        .subarray(0, 1024)
        .toString('utf-8')
        .trimStart()
        .toLowerCase();

    return dangerousTextPatterns.some((pattern) => head.startsWith(pattern));
}
